### ISSUE TITLE
可以交流一下吗

### ISSUE THREAD

**Issue by HEGGRIA** [FlandiaYingman/arkwaifu#13]
你好，我是 ArkSurvey 的 Maintainer HEGGRIA，由于网站刚刚起步缺乏很多基础设施，这几天想搭个 assets 工作流但由于本职前端阻力很大，翻阅 github 找轮子的时候看到大佬的项目很切中需求，所以提个 issue 问一下大佬有无兴趣交流交流（

**Comment by FlandiaYingman** [comment]
当然啦。有什么问题就问吧 🚀

**Comment by HEGGRIA** [comment]
请问解包Texture2D到图片是怎么实现的呢，比如我现在获取了一个ui_char_avatar_h1_skins_0.ab，怎么样把这个包转换成一张张的png同时保留字符串名称，现在我用assetstudio导出的Texture2D会丢失path信息，比如叫这个"SpriteAtlasTexture-UI_CHAR_AVATAR_H1_0-1024x1024-fmt34_alpha #202"，然后我导出assets.xml结果里面的信息也是差不多

**Comment by FlandiaYingman** [comment]
> 请问解包Texture2D到图片是怎么实现的呢，比如我现在获取了一个ui_char_avatar_h1_skins_0.ab，怎么样把这个包转换成一张张的png同时保留字符串名称，现在我用assetstudio导出的Texture2D会丢失path信息，比如叫这个"SpriteAtlasTexture-UI_CHAR_AVATAR_H1_0-1024x1024-fmt34_alpha #202"，然后我导出assets.xml结果里面的信息也是差不多

我在用 [UnityPy](https://github.com/K0lb3/UnityPy) 解包，所以可以自定义。用 AssetStudio 的话我也没研究过啦

**Comment by HEGGRIA** [comment]
> 我在用 [UnityPy](https://github.com/K0lb3/UnityPy) 解包，所以可以自定义。用 AssetStudio 的话我也没研究过啦

好的，多谢了，我去研究一下👍

**Comment by HEGGRIA** [comment]
好像这次大更后找不到模组的ab文件了😂我看prts也没上传

**Comment by HEGGRIA** [comment]
好像这次大更后找不到模组的ab文件了😂我看prts也没上传

**Comment by FlandiaYingman** [comment]
> 好像这次大更后找不到模组的ab文件了😂我看prts也没上传

来自PRTS站长：模组prts传了，虽然不是我传的 但是模组我看他们是找到了
来自朋友martin佬：模组叫uniqueequip，data里有啊

**Comment by HEGGRIA** [comment]
> 模组叫uniqueequip，data里有啊
我是在找模组的图片，Android 文件夹里面搜好像找不到，然后看文件大小也没有找到相近的

> 来自PRTS站长：模组prts传了，虽然不是我传的 但是模组我看他们是找到了
https://prts.wiki/index.php?title=%E7%89%B9%E6%AE%8A:%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6&wpDestFile=%E6%A8%A1%E7%BB%84_%E6%BA%90%E7%9F%B3%E9%AA%B0%E5%AD%90%E6%94%B6%E7%BA%B3%E7%9B%92.png
好像没上传，这次新增的模组还没有图片

**Comment by martinwang2002** [comment]
现在PRTS应该是已经解决了

> For reference only
> ab path:
> AK/CN/Android/assets/22-06-08-09-38-29-c966eb/assetbundle/spritepack/ui_equip_big_img_hub_h1_s_0.ab
> container path:
> AK/CN/Android/assets/22-06-08-09-38-29-c966eb/unpacked_assetbundle/assets/torappu/dynamicassets/arts/ui/uniequipimg
