### ISSUE TITLE
China CDN (Mirror)

### ISSUE THREAD

**Issue by FlandiaYingman** [FlandiaYingman/arkwaifu#32]

**Comment by nikolay167** [comment]
Hey! 

Incase you need help with China cdn, we have our own solution based on the wangsu cdn

**Comment by FlandiaYingman** [comment]
Thanks! I would like to know more about your solution :)

**Comment by nikolay167** [comment]
So technically we are using a wangsu network to distribute any type of content locally in China and wangsu known for the best network in Asia.

Incase you need ICP license for the distribution of the content, we can also provide it.


What type of content do you want to distribute (Live, static, dynamic ?)

Do you need a trial?

**Comment by FlandiaYingman** [comment]
Closed as not planned. Too expensive :<
